# Generated by Django 5.2.6 on 2025-09-18 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20, unique=True)),
                ('tier_level', models.IntegerField(unique=True)),
                ('min_points', models.IntegerField()),
                ('color', models.CharField(default='#CD7F32', max_length=7)),
                ('icon', models.CharField(default='🥉', max_length=50)),
                ('benefits', models.JSONField(default=list)),
                ('exclusive_offers', models.BooleanField(default=False)),
                ('premium_support', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tier_level'],
            },
        ),
        migrations.CreateModel(
            name='TierActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Daily Login'), ('transaction', 'Transaction'), ('redemption', 'Voucher Redemption'), ('referral', 'Referral'), ('review', 'Review'), ('social_share', 'Social Share')], max_length=20)),
                ('points_earned', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TierBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('benefit_type', models.CharField(choices=[('discount', 'Discount'), ('exclusive_offer', 'Exclusive Offer'), ('premium_support', 'Premium Support'), ('early_access', 'Early Access'), ('bonus_points', 'Bonus Points'), ('free_shipping', 'Free Shipping')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_benefits', to='accounts.rewardtier')),
            ],
        ),
        migrations.CreateModel(
            name='UserTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points_earned', models.IntegerField(default=0)),
                ('tier_points', models.IntegerField(default=0)),
                ('tier_start_date', models.DateTimeField(auto_now_add=True)),
                ('last_tier_upgrade', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rewardtier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
