# Generated by Django 5.2.6 on 2025-09-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rewardtier_tieractivity_tierbenefit_usertier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemption',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
