# Generated by Django 5.2.6 on 2025-10-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_minigame_gamesession_leaderboardentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.IntegerField(default=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active_days', models.CharField(default='0,1,2,3,4', help_text='Comma-separated day indices where 0=Mon ... 6=Sun', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='promotions', to='accounts.vouchercategory')),
            ],
        ),
    ]
